# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
use_frameworks!

target 'OurProjectBySwift' do
pod 'Alamofire', '~> 3.1.4'
pod 'Kingfisher', '~> 1.9'
pod 'SwiftyJSON', '~> 2.3.2'
pod 'MBProgressHUD', '~> 0.9.0'
end

target 'OurProjectBySwiftTests' do

end

target 'OurProjectBySwiftUITests' do

end

